<?php
// backend/api/chatbot.php

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

// Ensure user is authenticated
if (!isset($_SESSION['user_id']) || !isset($_SESSION['role'])) {
    echo json_encode([
        'status' => 'error',
        'message' => 'Unauthorized access',
        'in_scope' => false,
        'answer' => 'Unauthorized'
    ], JSON_UNESCAPED_UNICODE);
    exit;
}

$userRole = $_SESSION['role'];
$lang = $_SESSION['lang'] ?? 'vi';

// Giải phóng session lock ngay lập tức để không làm lag các trang khác
session_write_close();

require_once __DIR__ . '/../models/ChatbotModel.php';

try {
    // Đọc input JSON hoặc POST payload
    $rawInput = file_get_contents('php://input');
    $input = json_decode($rawInput, true);
    if (!is_array($input)) {
        $input = $_POST;
    }

    $message = trim($input['message'] ?? $input['prompt'] ?? '');

    if (empty($message)) {
        echo json_encode([
            'status' => 'error',
            'in_scope' => false,
            'answer' => ($lang === 'en') ? 'Please enter a message.' : 'Vui lòng nhập nội dung câu hỏi.'
        ], JSON_UNESCAPED_UNICODE);
        exit;
    }

    $chatbotModel = new ChatbotModel();
    $result = $chatbotModel->processQuery($message, $userRole, $lang);

    $disclaimer = ($lang === 'en')
        ? 'Result generated by AI — please cross-check with the official dashboard before making important decisions.'
        : 'Kết quả do AI tổng hợp, vui lòng đối chiếu dashboard chính thức trước khi ra quyết định quan trọng.';

    echo json_encode([
        'status' => 'success',
        'in_scope' => (bool)$result['in_scope'],
        'answer' => $result['answer'],
        'disclaimer' => $result['in_scope'] ? $disclaimer : null,
        'sql' => $result['sql'] ?? null
    ], JSON_UNESCAPED_UNICODE);

} catch (Exception $e) {
    echo json_encode([
        'status' => 'error',
        'in_scope' => false,
        'answer' => ($lang === 'en') 
            ? 'An internal error occurred. Please try again later.' 
            : 'Có lỗi hệ thống xảy ra. Vui lòng thử lại sau.'
    ], JSON_UNESCAPED_UNICODE);
}
?>
